name: Deploy to FTP
on:
  workflow_dispatch:

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ftp.lasso.cat
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public_html/
          server-dir: /domains/lasso.cat/public_html/
          protocol: ftp
          security: loose
